jobs:
  build:
    env:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out OFBiz sources
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
      with:
        cache: gradle
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Grant execute permission for gradlew and pullAllPluginsSource.sh
      run: chmod +x gradlew pullAllPluginsSource.sh
    - continue-on-error: true
      name: Load all plugins
      run: ./pullAllPluginsSource.sh
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew check javadoc
name: Java CI with Gradle
on:
  repository_dispatch:
    types: trigger-ga___gradle.yaml
permissions:
  contents: read
