jobs:
  analysis:
    name: Scorecard analysis
    permissions:
      id-token: write
      security-events: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        persist-credentials: false
    - continue-on-error: true
      name: Run analysis
      uses: ossf/scorecard-action@0864cf19026789058feabb7e87baa5f140aac736
      with:
        publish_results: ${{ !env.ACT }}
        results_file: results.sarif
        results_format: sarif
    - continue-on-error: true
      if: ${{ !env.ACT }}
      name: Upload artifact
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
      with:
        name: SARIF file
        path: results.sarif
        retention-days: 5
    - continue-on-error: true
      if: ${{ !env.ACT }}
      name: Upload to code-scanning
      uses: github/codeql-action/upload-sarif@cf7e9f23492505046de9a37830c3711dd0f25bb3
      with:
        sarif_file: results.sarif
name: Scorecard supply-chain security
on:
  repository_dispatch:
    types: trigger-ga___scorecard.yml
permissions: read-all
